name: alumni_network
description: A Flutter Alumni Network application for university graduates.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.0.5
  
  # HTTP Client
  dio: ^5.3.2
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # Navigation
  go_router: ^10.1.2
  
  # Image Handling
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  
  # Notifications
  flutter_local_notifications: ^19.3.0
  timezone: ^0.10.1
  
  # Charts
  fl_chart: ^0.65.0
  
  # Utilities
  intl: ^0.18.1
  url_launcher: ^6.1.14
  permission_handler: ^11.0.1
  
  # Security
  flutter_secure_storage: ^9.0.0
  
  # Connectivity
  connectivity_plus: ^4.0.2
  
  # UI Components
  cupertino_icons: ^1.0.2
  
  # Google Fonts
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
